trigger:
- main

pool:
  vmImage: windows-latest

variables:
  solutionName: Testing_Environment_Variables
  artifactName: powerplatform
  majorMinorVersion: 1.0
  managedZip: $(Build.ArtifactStagingDirectory)/$(solutionName)_managed.zip

stages:

# =========================================================
# STAGE 1 – EXPORT FROM SOURCE & DEPLOY TO ENV 1
# =========================================================
- stage: Export_And_Deploy_Env1
  displayName: Export from Source and Deploy to Env 1

  jobs:
  - job: Build_And_Deploy_Env1
    displayName: Export Managed Solution and Upgrade Env 1

    steps:
    - checkout: self

    - task: PowerPlatformToolInstaller@2
      displayName: Install Power Platform Tools

    # Auto Versioning
    - task: PowerPlatformSetSolutionVersion@2
      displayName: Set Solution Version
      inputs:
        authenticationType: PowerPlatformSPN
        PowerPlatformSPN: Test-WIF
        SolutionName: $(solutionName)
        SolutionVersionNumber: $(majorMinorVersion).$(Build.BuildId).0

    # Export Managed Solution
    - task: PowerPlatformExportSolution@2
      displayName: Export Managed Solution
      inputs:
        authenticationType: PowerPlatformSPN
        PowerPlatformSPN: Test-WIF
        SolutionName: $(solutionName)
        SolutionOutputFile: $(managedZip)
        Managed: true

    # Publish Artifact for next stages
    - task: PublishPipelineArtifact@1
      displayName: Publish Solution Artifact
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifact: $(artifactName)

    # ==============================
    # STAGE FOR UPGRADE – ENV 1
    # ==============================
    - task: PowerPlatformImportSolution@2
      displayName: Stage for Upgrade - Env 1
      inputs:
        authenticationType: PowerPlatformSPN
        PowerPlatformSPN: Test-Target-WIF
        SolutionInputFile: $(managedZip)
        ImportAsHoldingSolution: true
        UseDeploymentSettingsFile: true
        DeploymentSettingsFile: $(Build.SourcesDirectory)/Power_Pages/deploymentSettings.json
        PublishWorkflows: true
        AsyncOperation: true
        MaxAsyncWaitTime: 60

    # ==============================
    # APPLY UPGRADE – ENV 1
    # ==============================
    - task: PowerPlatformApplySolutionUpgrade@2
      displayName: Apply Upgrade - Env 1
      inputs:
        authenticationType: PowerPlatformSPN
        PowerPlatformSPN: Test-Target-WIF
        SolutionName: $(solutionName)
        AsyncOperation: true
        MaxAsyncWaitTime: 60


# =========================================================
# STAGE 2 – DEPLOY TO ENV 2 (APPROVAL REQUIRED)
# =========================================================
- stage: Deploy_Env2
  displayName: Deploy to Env 2
  dependsOn: Export_And_Deploy_Env1
  condition: succeeded()

  jobs:
  - deployment: Deploy_To_Env2
    displayName: Upgrade Solution in Env 2
    environment: Env2-Approval
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - task: PowerPlatformToolInstaller@2
            displayName: Install Power Platform Tools

          - task: DownloadPipelineArtifact@2
            displayName: Download Solution Artifact
            inputs:
              artifact: $(artifactName)
              path: $(Pipeline.Workspace)

          # ==============================
          # STAGE FOR UPGRADE – ENV 2
          # ==============================
          - task: PowerPlatformImportSolution@2
            displayName: Stage for Upgrade - Env 2
            inputs:
              authenticationType: PowerPlatformSPN
              PowerPlatformSPN: Test-WIF-Target-2
              SolutionInputFile: $(Pipeline.Workspace)/$(solutionName)_managed.zip
              ImportAsHoldingSolution: true
              UseDeploymentSettingsFile: true
              DeploymentSettingsFile: $(Build.SourcesDirectory)/Power_Pages/deploymentSettings-env2.json
              PublishWorkflows: true
              AsyncOperation: true
              MaxAsyncWaitTime: 60

          # ==============================
          # APPLY UPGRADE – ENV 2
          # ==============================
          - task: PowerPlatformApplySolutionUpgrade@2
            displayName: Apply Upgrade - Env 2
            inputs:
              authenticationType: PowerPlatformSPN
              PowerPlatformSPN: Test-WIF-Target-2
              SolutionName: $(solutionName)
              AsyncOperation: true
              MaxAsyncWaitTime: 60
