trigger:
- main

pool:
  vmImage: windows-latest

variables:
  solutionName: Testing_Environment_Variables
  artifactName: powerplatform
  majorMinorVersion: 1.0
  managedZip: $(Build.ArtifactStagingDirectory)/$(solutionName)_managed.zip

stages:

# =========================================================
# STAGE 1 – EXPORT FROM SOURCE & DEPLOY TO ENV 1
# =========================================================
- stage: Deploy_Env1
  displayName: Deploy to Env 1
  jobs:
  - job: DeployEnv1
    displayName: Export and Import to Env 1
    steps:
    - checkout: self

    - task: PowerPlatformToolInstaller@2
      displayName: Install Power Platform Tools

    # 🔥 Auto Set Version (DevOps Standard)
    - task: PowerPlatformSetSolutionVersion@2
      displayName: Set Solution Version Automatically
      inputs:
        authenticationType: PowerPlatformSPN
        PowerPlatformSPN: Test-WIF
        SolutionName: $(solutionName)
        SolutionVersionNumber: $(majorMinorVersion).$(Build.BuildId).0

    - task: PowerPlatformExportSolution@2
      displayName: Export Managed Solution
      inputs:
        authenticationType: PowerPlatformSPN
        PowerPlatformSPN: Test-WIF
        SolutionName: $(solutionName)
        SolutionOutputFile: $(managedZip)
        Managed: true

    - task: PublishPipelineArtifact@1
      displayName: Publish Solution Artifact
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifact: $(artifactName)

    - task: DownloadPipelineArtifact@2
      displayName: Download Solution Artifact
      inputs:
        artifact: $(artifactName)
        path: $(Pipeline.Workspace)

    # 🔥 Import as UPGRADE (Correct ALM)
    - task: PowerPlatformImportSolution@2
      displayName: Import to Env 1 (Upgrade Mode)
      inputs:
        authenticationType: PowerPlatformSPN
        PowerPlatformSPN: Test-Target-WIF
        SolutionInputFile: $(Pipeline.Workspace)/$(solutionName)_managed.zip
        Managed: true
        ImportAsHoldingSolution: false
        OverwriteUnmanagedCustomizations: true
        UseDeploymentSettingsFile: true
        DeploymentSettingsFile: $(Build.SourcesDirectory)/Power_Pages/deploymentSettings.json
        PublishWorkflows: true
        AsyncOperation: true
        MaxAsyncWaitTime: 60


# =========================================================
# STAGE 2 – DEPLOY TO ENV 2 (APPROVAL REQUIRED)
# =========================================================
- stage: Deploy_Env2
  displayName: Deploy to Env 2 (Approval Required)
  dependsOn: Deploy_Env1
  condition: succeeded()

  jobs:
  - deployment: DeployEnv2
    displayName: Deploy to Env 2
    environment: Preetham
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - task: PowerPlatformToolInstaller@2
            displayName: Install Power Platform Tools

          - task: DownloadPipelineArtifact@2
            displayName: Download Solution Artifact
            inputs:
              artifact: $(artifactName)
              path: $(Pipeline.Workspace)

          # 🔥 Always Upgrade
          - task: PowerPlatformImportSolution@2
            displayName: Import to Env 2 (Upgrade Mode)
            inputs:
              authenticationType: PowerPlatformSPN
              PowerPlatformSPN: Test-WIF-Target-2
              SolutionInputFile: $(Pipeline.Workspace)/$(solutionName)_managed.zip
              Managed: true
              ImportAsHoldingSolution: false
              OverwriteUnmanagedCustomizations: true
              UseDeploymentSettingsFile: true
              DeploymentSettingsFile: $(Build.SourcesDirectory)/Power_Pages/deploymentSettings-env2.json
              PublishWorkflows: true
              AsyncOperation: true
              MaxAsyncWaitTime: 60
